http:
  port: ${PORT:-8080}
  host: ${LOCAL_IP:-localhost}
admin:
  port: 9876
##################################################################################################
apiEndpoints:
  api:
    paths: ["/ip", "/ip/*"]
  auth:
    paths: ["/auth/", "/auth/*"]
  users:
    methods: "GET,POST,PUT,PATCH,DELETE"
    paths: ["/users", "/users/*"]
  account:
    paths: ["/accounts", "/accounts/*"]
  admin:
    paths: "/admin/*"
  transaction:
    paths: ["/transaction", "/transaction/*"]
  email:
    paths: ["/email", "/email/*"]
  contact:
    paths: ["/contacts", "/contacts/*"]
  statistics:
    paths: ["/statistics", "/statistics/*"]
  whatsapp:
    paths: ["/whatsapp", "/whatsapp/*"]
  interoperabilities:
    paths: ["/interoperabilities", "/interoperabilities/*"]

##################################################################################################
serviceEndpoints:
  usersService:
    url: "http://${LOCAL_IP:-localhost}:8000"
  transactionService:
    url: "http://${LOCAL_IP:-localhost}:8001"
  authService:
    url: "http://${LOCAL_IP:-localhost}:8002"
  accountService:
    url: "http://${LOCAL_IP:-localhost}:8004"
  adminService:
    url: "http://${LOCAL_IP:-localhost}:8003"
  emailService:
    url: "http://${LOCAL_IP:-localhost}:8005"
  contactService:
    url: "http://${LOCAL_IP:-localhost}:8006"
  statisticsService:
    url: "http://${LOCAL_IP:-localhost}:8008"
  whatsappService:
    url: "http://${LOCAL_IP:-localhost}:8007"
  interoperabilitiesService:
    url: "http://${LOCAL_IP:-localhost}:8009"
##################################################################################################
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - oauth2
  - proxy
  - rate-limit
  - log
  - jwt
  - request-transformer
pipelines:
  ##################################################################################################
  usersPipeline:
    apiEndpoints:
      - users
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      # - jwt:
      #   - action:
      #       secretOrPublicKey: 'mobaAuth'
      #       checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true

  ##################################################################################################
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  ##################################################################################################
  accountPipeline:
    apiEndpoints:
      - account
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      # - jwt:
      #   - action:
      #       secretOrPublicKey: 'mobaAuth'
      #       checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: accountService
              changeOrigin: true

  ##################################################################################################
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true
  ##################################################################################################
  transactionPipeline:
    apiEndpoints:
      - transaction
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: transactionService
              changeOrigin: true
##################################################################################################
  emailPipeline:
    apiEndpoints:
      - email
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: emailService
              stripPath: true
              changeOrigin: true
##################################################################################################
  contactPipeline:
    apiEndpoints:
      - contact
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: contactService
              stripPath: true
              changeOrigin: true
##################################################################################################
  whatsappPipeline:
    apiEndpoints:
      - whatsapp
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: whatsappService
              stripPath: true
              changeOrigin: true
##################################################################################################
  statisticsPipeline:
    apiEndpoints:
      - statistics
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: statisticsService
              changeOrigin: true
##################################################################################################
  interoperabilitiesPipeline:
    apiEndpoints:
      - interoperabilities
    policies:
      - log:
          - action:
              message: "local_ip ===> ${LOCAL_IP:-localhost}"
      - proxy:
          - action:
              serviceEndpoint: interoperabilitiesService
              stripPath: true
              changeOrigin: true